/**
 * Official public past-paper resources that are useful for ESAT preparation.
 *
 * Every URL points at the official UAT-UK copy of the document. We deliberately
 * do not rehost any PDF: the official page is the only place guaranteed to carry
 * the current version, including the out-of-spec markings UAT-UK adds. Only
 * metadata, links and our own labels live in this file.
 *
 * Links were harvested from the official archive pages and each one was checked
 * to resolve on 26 July 2026.
 */

export type PastPaperExam = "ENGAA" | "NSAA" | "TMUA";

export type EsatModule =
  | "Mathematics 1"
  | "Mathematics 2"
  | "Physics"
  | "Chemistry"
  | "Biology";

export type PaperResourceType = "question-paper" | "specimen";

/** How closely a resource matches what the ESAT actually asks. */
export type RelevanceLevel = "high" | "medium" | "low";

/**
 * How far we have checked the questions inside a resource.
 * - verified: questions compared against the official PDF text
 * - likely: compared, with some questions the extraction could not split cleanly
 * - unverified: listed from the official archive, not yet checked question by question
 */
export type MappingStatus = "verified" | "likely" | "unverified";

export type PastPaperResource = {
  id: string;
  exam: PastPaperExam;
  /** Null for the undated early specimen papers. */
  year: number | null;
  paperName: string;
  sectionName: string;
  resourceType: PaperResourceType;
  questionPaperUrl: string;
  answerKeyUrl: string | null;
  workedSolutionsUrl: string | null;
  officialSourcePage: string;
  bestForModules: readonly EsatModule[];
  relevanceLevel: RelevanceLevel;
  notes: string;
  mappingStatus: MappingStatus;
  copyrightNotice: string;
};

export const PAST_PAPERS: readonly PastPaperResource[] = [
  {
    id: "engaa-2016-s1",
    exam: "ENGAA",
    year: 2016,
    paperName: "ENGAA 2016",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07112055/ENGAA_2016_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07112109/ENGAA_2016_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 39 of the 40 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2017-s1",
    exam: "ENGAA",
    year: 2017,
    paperName: "ENGAA 2017",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07112231/ENGAA_2017_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07112228/ENGAA_2017_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 38 of the 40 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2018-s1",
    exam: "ENGAA",
    year: 2018,
    paperName: "ENGAA 2018",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07113017/ENGAA_2018_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07113023/ENGAA_2018_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 39 of the 40 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2019-s1",
    exam: "ENGAA",
    year: 2019,
    paperName: "ENGAA 2019",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115511/ENGAA_2019_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115515/ENGAA_2019_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 36 of the 40 questions in this PDF.",
    mappingStatus: "likely",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2020-s1",
    exam: "ENGAA",
    year: 2020,
    paperName: "ENGAA 2020",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115613/ENGAA_2020_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115614/ENGAA_2020_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2021-s1",
    exam: "ENGAA",
    year: 2021,
    paperName: "ENGAA 2021",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115611/ENGAA_2021_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115613/ENGAA_2021_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 38 of the 40 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2022-s1",
    exam: "ENGAA",
    year: 2022,
    paperName: "ENGAA 2022",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115611/ENGAA_2022_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115612/ENGAA_2022_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper. Our duplicate check could read 37 of the 40 questions in this PDF.",
    mappingStatus: "likely",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "engaa-2023-s1",
    exam: "ENGAA",
    year: 2023,
    paperName: "ENGAA 2023",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115605/ENGAA_2023_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07115610/ENGAA_2023_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics"],
    relevanceLevel: "high",
    notes: "Part A is Mathematics and Physics; Part B is Advanced Mathematics and Advanced Physics. Closest legacy match for ESAT Maths 1, Maths 2 and Physics. Overlaps heavily with the same year's NSAA paper.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2016-s1",
    exam: "NSAA",
    year: 2016,
    paperName: "NSAA 2016",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120539/NSAA_2016_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120540/NSAA_2016_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry, Part D Biology and Part E Advanced Mathematics and Advanced Physics. The only legacy archive covering Chemistry and Biology, and Part E is useful Maths 2 material. Parts A, B and E repeat many ENGAA questions from the same year. Our duplicate check could read 79 of the 80 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2017-s1",
    exam: "NSAA",
    year: 2017,
    paperName: "NSAA 2017",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120538/NSAA_2017_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120538/NSAA_2017_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry, Part D Biology and Part E Advanced Mathematics and Advanced Physics. The only legacy archive covering Chemistry and Biology, and Part E is useful Maths 2 material. Parts A, B and E repeat many ENGAA questions from the same year. Our duplicate check could read 75 of the 80 questions in this PDF.",
    mappingStatus: "likely",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2018-s1",
    exam: "NSAA",
    year: 2018,
    paperName: "NSAA 2018",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120537/NSAA_2018_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120537/NSAA_2018_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry, Part D Biology and Part E Advanced Mathematics and Advanced Physics. The only legacy archive covering Chemistry and Biology, and Part E is useful Maths 2 material. Parts A, B and E repeat many ENGAA questions from the same year. Our duplicate check could read 78 of the 80 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2019-s1",
    exam: "NSAA",
    year: 2019,
    paperName: "NSAA 2019",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120534/NSAA_2019_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120535/NSAA_2019_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Mathematics 2", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry, Part D Biology and Part E Advanced Mathematics and Advanced Physics. The only legacy archive covering Chemistry and Biology, and Part E is useful Maths 2 material. Parts A, B and E repeat many ENGAA questions from the same year. Our duplicate check could read 75 of the 80 questions in this PDF.",
    mappingStatus: "likely",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2020-s1",
    exam: "NSAA",
    year: 2020,
    paperName: "NSAA 2020",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120533/NSAA_2020_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120535/NSAA_2020_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry and Part D Biology. No advanced part from 2020 onwards, so ENGAA is the better source for Maths 2. Parts A and B repeat many ENGAA questions from the same year.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2021-s1",
    exam: "NSAA",
    year: 2021,
    paperName: "NSAA 2021",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120532/NSAA_2021_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120532/NSAA_2021_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry and Part D Biology. No advanced part from 2020 onwards, so ENGAA is the better source for Maths 2. Parts A and B repeat many ENGAA questions from the same year. Our duplicate check could read 70 of the 80 questions in this PDF.",
    mappingStatus: "likely",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2022-s1",
    exam: "NSAA",
    year: 2022,
    paperName: "NSAA 2022",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120525/NSAA_2022_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120531/NSAA_2022_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry and Part D Biology. No advanced part from 2020 onwards, so ENGAA is the better source for Maths 2. Parts A and B repeat many ENGAA questions from the same year. Our duplicate check could read 76 of the 80 questions in this PDF.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "nsaa-2023-s1",
    exam: "NSAA",
    year: 2023,
    paperName: "NSAA 2023",
    sectionName: "Section 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120523/NSAA_2023_S1_QuestionPaper.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07120531/NSAA_2023_S1_AnswerKey.pdf",
    workedSolutionsUrl: null,
    officialSourcePage: "https://esat-tmua.ac.uk/esat-preparation-materials/",
    bestForModules: ["Mathematics 1", "Physics", "Chemistry", "Biology"],
    relevanceLevel: "high",
    notes: "Part A Mathematics, Part B Physics, Part C Chemistry and Part D Biology. No advanced part from 2020 onwards, so ENGAA is the better source for Maths 2. Parts A and B repeat many ENGAA questions from the same year.",
    mappingStatus: "verified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2016-paper-1",
    exam: "TMUA",
    year: 2016,
    paperName: "TMUA 2016",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125112/TMUA-2016-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125113/TMUA-2016-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125113/TMUA-2016-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2016-paper-2",
    exam: "TMUA",
    year: 2016,
    paperName: "TMUA 2016",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125102/TMUA-2016-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125113/TMUA-2016-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125106/TMUA-2016-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2017-paper-1",
    exam: "TMUA",
    year: 2017,
    paperName: "TMUA 2017",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125230/TMUA-2017-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125232/TMUA-2017-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125231/TMUA-2017-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2017-paper-2",
    exam: "TMUA",
    year: 2017,
    paperName: "TMUA 2017",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125224/TMUA-2017-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125232/TMUA-2017-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125228/TMUA-2017-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2018-paper-1",
    exam: "TMUA",
    year: 2018,
    paperName: "TMUA 2018",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125407/TMUA-2018-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125413/TMUA-2018-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125413/TMUA-2018-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2018-paper-2",
    exam: "TMUA",
    year: 2018,
    paperName: "TMUA 2018",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125404/TMUA-2018-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125413/TMUA-2018-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07125406/TMUA-2018-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2019-paper-1",
    exam: "TMUA",
    year: 2019,
    paperName: "TMUA 2019",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140825/TMUA-2019-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140827/TMUA-2019-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140826/TMUA-2019-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2019-paper-2",
    exam: "TMUA",
    year: 2019,
    paperName: "TMUA 2019",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140823/TMUA-2019-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140827/TMUA-2019-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140824/TMUA-2019-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2020-paper-1",
    exam: "TMUA",
    year: 2020,
    paperName: "TMUA 2020",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140953/TMUA-2020-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140956/TMUA-2020-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140955/TMUA-2020-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2020-paper-2",
    exam: "TMUA",
    year: 2020,
    paperName: "TMUA 2020",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140951/TMUA-2020-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140956/TMUA-2020-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07140952/TMUA-2020-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2021-paper-1",
    exam: "TMUA",
    year: 2021,
    paperName: "TMUA 2021",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141119/TMUA-2021-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141122/TMUA-2021-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141121/TMUA-2021-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2021-paper-2",
    exam: "TMUA",
    year: 2021,
    paperName: "TMUA 2021",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141117/TMUA-2021-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141122/TMUA-2021-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141118/TMUA-2021-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2022-paper-1",
    exam: "TMUA",
    year: 2022,
    paperName: "TMUA 2022",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141241/TMUA-2022-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141242/TMUA-2022-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/06/04105226/TMUA-2022-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2022-paper-2",
    exam: "TMUA",
    year: 2022,
    paperName: "TMUA 2022",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141239/TMUA-2022-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141242/TMUA-2022-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/06/04105227/TMUA-2022-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2023-paper-1",
    exam: "TMUA",
    year: 2023,
    paperName: "TMUA 2023",
    sectionName: "Paper 1",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/04/30144109/TMUA-2023-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/04/30144123/TMUA-2023-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/06/04105227/TMUA-2023-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "medium",
    notes: "Applications of mathematical knowledge. The closest TMUA paper to ESAT Maths 2 reasoning, and useful non-calculator algebra practice.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-2023-paper-2",
    exam: "TMUA",
    year: 2023,
    paperName: "TMUA 2023",
    sectionName: "Paper 2",
    resourceType: "question-paper",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/04/30144111/TMUA-2023-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/04/30144123/TMUA-2023-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/06/04105226/TMUA-2023-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Mathematical reasoning: logic, proof and identifying flawed arguments. Good thinking practice but the format is not an ESAT substitute.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-specimen-paper-1",
    exam: "TMUA",
    year: null,
    paperName: "TMUA early specimen",
    sectionName: "Paper 1",
    resourceType: "specimen",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141417/TMUA-early-specimen-paper-1.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141414/TMUA-early-specimen-paper-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141418/TMUA-early-specimen-paper-1-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: ["Mathematics 2"],
    relevanceLevel: "low",
    notes: "Undated early specimen paper. Useful as extra material once the dated papers are used up.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
  {
    id: "tmua-specimen-paper-2",
    exam: "TMUA",
    year: null,
    paperName: "TMUA early specimen",
    sectionName: "Paper 2",
    resourceType: "specimen",
    questionPaperUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141413/TMUA-early-specimen-paper-2.pdf",
    answerKeyUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141414/TMUA-early-specimen-paper-answer-keys.pdf",
    workedSolutionsUrl: "https://uat-wp.s3.eu-west-2.amazonaws.com/wp-content/uploads/2024/05/07141415/TMUA-early-specimen-paper-2-worked-answers.pdf",
    officialSourcePage: "https://esat-tmua.ac.uk/tmua-preparation-materials/",
    bestForModules: [],
    relevanceLevel: "low",
    notes: "Undated early specimen paper. Useful as extra material once the dated papers are used up.",
    mappingStatus: "unverified",
    copyrightNotice: "© Cambridge University Press & Assessment. Published by UAT-UK. Linked from the official source, not rehosted here.",
  },
];

export const PAST_PAPER_EXAMS: readonly PastPaperExam[] = ["ENGAA", "NSAA", "TMUA"];

export const ESAT_MODULES: readonly EsatModule[] = [
  "Mathematics 1",
  "Mathematics 2",
  "Physics",
  "Chemistry",
  "Biology",
];

/** Descending, so the most recent papers come first. */
export const PAST_PAPER_YEARS: readonly number[] = Array.from(
  new Set(
    PAST_PAPERS.map((paper) => paper.year).filter(
      (year): year is number => year !== null,
    ),
  ),
).sort((a, b) => b - a);

export function papersByExam(exam: PastPaperExam): readonly PastPaperResource[] {
  return PAST_PAPERS.filter((paper) => paper.exam === exam);
}
