/**
 * Groups of questions that are the same question published in more than one
 * paper. A group collapses to a single piece of practice: solving every member
 * of a group is not extra evidence about your score.
 *
 * `verified: true` means the extracted text of the official PDFs matched at 97%
 * or above. `verified: false` means the match was between 90% and 97%, which is
 * almost always the same question with PDF extraction noise, but we label it
 * separately rather than overstate it.
 */

import { PAST_PAPER_QUESTION_MAP } from "@/content/pastPaperQuestionMap";

export type PastPaperDuplicateGroup = {
  id: string;
  title: string;
  verified: boolean;
  canonicalQuestionId: string;
  duplicateQuestionIds: readonly string[];
  notes: string;
};

export const PAST_PAPER_DUPLICATE_GROUPS: readonly PastPaperDuplicateGroup[] = [
  {
    id: "dup-2016-engaa-q4-nsaa-q22",
    title: "2016: ENGAA Part A Mathematics and Physics Q4 and NSAA Part B Physics Q22",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q4",
    duplicateQuestionIds: ["nsaa-2016-s1-q22"],
    notes: "Automated text comparison of the official PDFs scored 98.1%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q6-nsaa-q23",
    title: "2016: ENGAA Part A Mathematics and Physics Q6 and NSAA Part B Physics Q23",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q6",
    duplicateQuestionIds: ["nsaa-2016-s1-q23"],
    notes: "Automated text comparison of the official PDFs scored 97.5%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q7-nsaa-q4",
    title: "2016: ENGAA Part A Mathematics and Physics Q7 and NSAA Part A Mathematics Q4",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q7",
    duplicateQuestionIds: ["nsaa-2016-s1-q4"],
    notes: "Automated text comparison of the official PDFs scored 93.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q8-nsaa-q24",
    title: "2016: ENGAA Part A Mathematics and Physics Q8 and NSAA Part B Physics Q24",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q8",
    duplicateQuestionIds: ["nsaa-2016-s1-q24"],
    notes: "Automated text comparison of the official PDFs scored 97.1%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q9-nsaa-q5",
    title: "2016: ENGAA Part A Mathematics and Physics Q9 and NSAA Part A Mathematics Q5",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q9",
    duplicateQuestionIds: ["nsaa-2016-s1-q5"],
    notes: "Automated text comparison of the official PDFs scored 99.5%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q10-nsaa-q26",
    title: "2016: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q26",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q10",
    duplicateQuestionIds: ["nsaa-2016-s1-q26"],
    notes: "Automated text comparison of the official PDFs scored 99.6%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q11-nsaa-q6",
    title: "2016: ENGAA Part A Mathematics and Physics Q11 and NSAA Part A Mathematics Q6",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q11",
    duplicateQuestionIds: ["nsaa-2016-s1-q6"],
    notes: "Automated text comparison of the official PDFs scored 93.7%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q12-nsaa-q27",
    title: "2016: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q27",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q12",
    duplicateQuestionIds: ["nsaa-2016-s1-q27"],
    notes: "Automated text comparison of the official PDFs scored 96%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q15-nsaa-q8",
    title: "2016: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q8",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q15",
    duplicateQuestionIds: ["nsaa-2016-s1-q8"],
    notes: "Automated text comparison of the official PDFs scored 94.2%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q17-nsaa-q9",
    title: "2016: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q9",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q17",
    duplicateQuestionIds: ["nsaa-2016-s1-q9"],
    notes: "Automated text comparison of the official PDFs scored 93.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q18-nsaa-q30",
    title: "2016: ENGAA Part A Mathematics and Physics Q18 and NSAA Part B Physics Q30",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q18",
    duplicateQuestionIds: ["nsaa-2016-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 95.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q19-nsaa-q10",
    title: "2016: ENGAA Part A Mathematics and Physics Q19 and NSAA Part A Mathematics Q10",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q19",
    duplicateQuestionIds: ["nsaa-2016-s1-q10"],
    notes: "Automated text comparison of the official PDFs scored 95.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q20-nsaa-q31",
    title: "2016: ENGAA Part A Mathematics and Physics Q20 and NSAA Part B Physics Q31",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q20",
    duplicateQuestionIds: ["nsaa-2016-s1-q31"],
    notes: "Automated text comparison of the official PDFs scored 98.6%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q22-nsaa-q32",
    title: "2016: ENGAA Part A Mathematics and Physics Q22 and NSAA Part B Physics Q32",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q22",
    duplicateQuestionIds: ["nsaa-2016-s1-q32"],
    notes: "Automated text comparison of the official PDFs scored 95.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q23-nsaa-q12",
    title: "2016: ENGAA Part A Mathematics and Physics Q23 and NSAA Part A Mathematics Q12",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q23",
    duplicateQuestionIds: ["nsaa-2016-s1-q12"],
    notes: "Automated text comparison of the official PDFs scored 95.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q24-nsaa-q34",
    title: "2016: ENGAA Part A Mathematics and Physics Q24 and NSAA Part B Physics Q34",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q24",
    duplicateQuestionIds: ["nsaa-2016-s1-q34"],
    notes: "Automated text comparison of the official PDFs scored 95.2%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q26-nsaa-q35",
    title: "2016: ENGAA Part A Mathematics and Physics Q26 and NSAA Part B Physics Q35",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q26",
    duplicateQuestionIds: ["nsaa-2016-s1-q35"],
    notes: "Automated text comparison of the official PDFs scored 94.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q27-nsaa-q14",
    title: "2016: ENGAA Part A Mathematics and Physics Q27 and NSAA Part A Mathematics Q14",
    verified: true,
    canonicalQuestionId: "engaa-2016-s1-q27",
    duplicateQuestionIds: ["nsaa-2016-s1-q14"],
    notes: "Automated text comparison of the official PDFs scored 97.3%. Treated as the same question.",
  },
  {
    id: "dup-2016-engaa-q29-nsaa-q73",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q29 and NSAA Part E Advanced Mathematics and Advanced Physics Q73",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q29",
    duplicateQuestionIds: ["nsaa-2016-s1-q73"],
    notes: "Automated text comparison of the official PDFs scored 91.1%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q31-nsaa-q75",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q31 and NSAA Part E Advanced Mathematics and Advanced Physics Q75",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q31",
    duplicateQuestionIds: ["nsaa-2016-s1-q75"],
    notes: "Automated text comparison of the official PDFs scored 93.2%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q33-nsaa-q77",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q33 and NSAA Part E Advanced Mathematics and Advanced Physics Q77",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q33",
    duplicateQuestionIds: ["nsaa-2016-s1-q77"],
    notes: "Automated text comparison of the official PDFs scored 93.4%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q34-nsaa-q76",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q34 and NSAA Part E Advanced Mathematics and Advanced Physics Q76",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q34",
    duplicateQuestionIds: ["nsaa-2016-s1-q76"],
    notes: "Automated text comparison of the official PDFs scored 95.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q35-nsaa-q79",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q35 and NSAA Part E Advanced Mathematics and Advanced Physics Q79",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q35",
    duplicateQuestionIds: ["nsaa-2016-s1-q79"],
    notes: "Automated text comparison of the official PDFs scored 93%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2016-engaa-q36-nsaa-q78",
    title: "2016: ENGAA Part B Advanced Mathematics and Advanced Physics Q36 and NSAA Part E Advanced Mathematics and Advanced Physics Q78",
    verified: false,
    canonicalQuestionId: "engaa-2016-s1-q36",
    duplicateQuestionIds: ["nsaa-2016-s1-q78"],
    notes: "Automated text comparison of the official PDFs scored 96.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q4-nsaa-q21",
    title: "2017: ENGAA Part A Mathematics and Physics Q4 and NSAA Part B Physics Q21",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q4",
    duplicateQuestionIds: ["nsaa-2017-s1-q21"],
    notes: "Automated text comparison of the official PDFs scored 93.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q6-nsaa-q24",
    title: "2017: ENGAA Part A Mathematics and Physics Q6 and NSAA Part B Physics Q24",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q6",
    duplicateQuestionIds: ["nsaa-2017-s1-q24"],
    notes: "Automated text comparison of the official PDFs scored 95.1%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q7-nsaa-q4",
    title: "2017: ENGAA Part A Mathematics and Physics Q7 and NSAA Part A Mathematics Q4",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q7",
    duplicateQuestionIds: ["nsaa-2017-s1-q4"],
    notes: "Automated text comparison of the official PDFs scored 94.5%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q9-nsaa-q5",
    title: "2017: ENGAA Part A Mathematics and Physics Q9 and NSAA Part A Mathematics Q5",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q9",
    duplicateQuestionIds: ["nsaa-2017-s1-q5"],
    notes: "Automated text comparison of the official PDFs scored 94.1%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q12-nsaa-q26",
    title: "2017: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q26",
    verified: true,
    canonicalQuestionId: "engaa-2017-s1-q12",
    duplicateQuestionIds: ["nsaa-2017-s1-q26"],
    notes: "Automated text comparison of the official PDFs scored 97.6%. Treated as the same question.",
  },
  {
    id: "dup-2017-engaa-q14-nsaa-q27",
    title: "2017: ENGAA Part A Mathematics and Physics Q14 and NSAA Part B Physics Q27",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q14",
    duplicateQuestionIds: ["nsaa-2017-s1-q27"],
    notes: "Automated text comparison of the official PDFs scored 94.4%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q15-nsaa-q10",
    title: "2017: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q10",
    verified: true,
    canonicalQuestionId: "engaa-2017-s1-q15",
    duplicateQuestionIds: ["nsaa-2017-s1-q10"],
    notes: "Automated text comparison of the official PDFs scored 98.1%. Treated as the same question.",
  },
  {
    id: "dup-2017-engaa-q16-nsaa-q28",
    title: "2017: ENGAA Part A Mathematics and Physics Q16 and NSAA Part B Physics Q28",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q16",
    duplicateQuestionIds: ["nsaa-2017-s1-q28"],
    notes: "Automated text comparison of the official PDFs scored 93.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q17-nsaa-q11",
    title: "2017: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q11",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q17",
    duplicateQuestionIds: ["nsaa-2017-s1-q11"],
    notes: "Automated text comparison of the official PDFs scored 96.5%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q18-nsaa-q29",
    title: "2017: ENGAA Part A Mathematics and Physics Q18 and NSAA Part B Physics Q29",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q18",
    duplicateQuestionIds: ["nsaa-2017-s1-q29"],
    notes: "Automated text comparison of the official PDFs scored 93.7%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q20-nsaa-q30",
    title: "2017: ENGAA Part A Mathematics and Physics Q20 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2017-s1-q20",
    duplicateQuestionIds: ["nsaa-2017-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 99.7%. Treated as the same question.",
  },
  {
    id: "dup-2017-engaa-q22-nsaa-q31",
    title: "2017: ENGAA Part A Mathematics and Physics Q22 and NSAA Part B Physics Q31",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q22",
    duplicateQuestionIds: ["nsaa-2017-s1-q31"],
    notes: "Automated text comparison of the official PDFs scored 96.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q24-nsaa-q33",
    title: "2017: ENGAA Part A Mathematics and Physics Q24 and NSAA Part B Physics Q33",
    verified: true,
    canonicalQuestionId: "engaa-2017-s1-q24",
    duplicateQuestionIds: ["nsaa-2017-s1-q33"],
    notes: "Automated text comparison of the official PDFs scored 97.4%. Treated as the same question.",
  },
  {
    id: "dup-2017-engaa-q25-nsaa-q16",
    title: "2017: ENGAA Part A Mathematics and Physics Q25 and NSAA Part A Mathematics Q16",
    verified: true,
    canonicalQuestionId: "engaa-2017-s1-q25",
    duplicateQuestionIds: ["nsaa-2017-s1-q16"],
    notes: "Automated text comparison of the official PDFs scored 97%. Treated as the same question.",
  },
  {
    id: "dup-2017-engaa-q26-nsaa-q34",
    title: "2017: ENGAA Part A Mathematics and Physics Q26 and NSAA Part B Physics Q34",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q26",
    duplicateQuestionIds: ["nsaa-2017-s1-q34"],
    notes: "Automated text comparison of the official PDFs scored 96%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q30-nsaa-q74",
    title: "2017: ENGAA Part B Advanced Mathematics and Advanced Physics Q30 and NSAA Part E Advanced Mathematics and Advanced Physics Q74",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q30",
    duplicateQuestionIds: ["nsaa-2017-s1-q74"],
    notes: "Automated text comparison of the official PDFs scored 95.1%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q34-nsaa-q76",
    title: "2017: ENGAA Part B Advanced Mathematics and Advanced Physics Q34 and NSAA Part E Advanced Mathematics and Advanced Physics Q76",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q34",
    duplicateQuestionIds: ["nsaa-2017-s1-q76"],
    notes: "Automated text comparison of the official PDFs scored 95.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2017-engaa-q38-nsaa-q78",
    title: "2017: ENGAA Part B Advanced Mathematics and Advanced Physics Q38 and NSAA Part E Advanced Mathematics and Advanced Physics Q78",
    verified: false,
    canonicalQuestionId: "engaa-2017-s1-q38",
    duplicateQuestionIds: ["nsaa-2017-s1-q78"],
    notes: "Automated text comparison of the official PDFs scored 96.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q1-nsaa-q1",
    title: "2018: ENGAA Part A Mathematics and Physics Q1 and NSAA Part A Mathematics Q1",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q1",
    duplicateQuestionIds: ["nsaa-2018-s1-q1"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q2-nsaa-q19",
    title: "2018: ENGAA Part A Mathematics and Physics Q2 and NSAA Part B Physics Q19",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q2",
    duplicateQuestionIds: ["nsaa-2018-s1-q19"],
    notes: "Automated text comparison of the official PDFs scored 98.8%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q3-nsaa-q2",
    title: "2018: ENGAA Part A Mathematics and Physics Q3 and NSAA Part A Mathematics Q2",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q3",
    duplicateQuestionIds: ["nsaa-2018-s1-q2"],
    notes: "Automated text comparison of the official PDFs scored 97.1%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q4-nsaa-q20",
    title: "2018: ENGAA Part A Mathematics and Physics Q4 and NSAA Part B Physics Q20",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q4",
    duplicateQuestionIds: ["nsaa-2018-s1-q20"],
    notes: "Automated text comparison of the official PDFs scored 95%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q6-nsaa-q21",
    title: "2018: ENGAA Part A Mathematics and Physics Q6 and NSAA Part B Physics Q21",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q6",
    duplicateQuestionIds: ["nsaa-2018-s1-q21"],
    notes: "Automated text comparison of the official PDFs scored 98.4%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q12-nsaa-q26",
    title: "2018: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q26",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q12",
    duplicateQuestionIds: ["nsaa-2018-s1-q26"],
    notes: "Automated text comparison of the official PDFs scored 94.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q13-nsaa-q9",
    title: "2018: ENGAA Part A Mathematics and Physics Q13 and NSAA Part A Mathematics Q9",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q13",
    duplicateQuestionIds: ["nsaa-2018-s1-q9"],
    notes: "Automated text comparison of the official PDFs scored 97%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q14-nsaa-q27",
    title: "2018: ENGAA Part A Mathematics and Physics Q14 and NSAA Part B Physics Q27",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q14",
    duplicateQuestionIds: ["nsaa-2018-s1-q27"],
    notes: "Automated text comparison of the official PDFs scored 98.4%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q15-nsaa-q10",
    title: "2018: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q10",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q15",
    duplicateQuestionIds: ["nsaa-2018-s1-q10"],
    notes: "Automated text comparison of the official PDFs scored 93.5%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q16-nsaa-q28",
    title: "2018: ENGAA Part A Mathematics and Physics Q16 and NSAA Part B Physics Q28",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q16",
    duplicateQuestionIds: ["nsaa-2018-s1-q28"],
    notes: "Automated text comparison of the official PDFs scored 99.3%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q17-nsaa-q11",
    title: "2018: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q11",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q17",
    duplicateQuestionIds: ["nsaa-2018-s1-q11"],
    notes: "Automated text comparison of the official PDFs scored 99%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q18-nsaa-q29",
    title: "2018: ENGAA Part A Mathematics and Physics Q18 and NSAA Part B Physics Q29",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q18",
    duplicateQuestionIds: ["nsaa-2018-s1-q29"],
    notes: "Automated text comparison of the official PDFs scored 99.2%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q19-nsaa-q13",
    title: "2018: ENGAA Part A Mathematics and Physics Q19 and NSAA Part A Mathematics Q13",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q19",
    duplicateQuestionIds: ["nsaa-2018-s1-q13"],
    notes: "Automated text comparison of the official PDFs scored 98.1%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q20-nsaa-q30",
    title: "2018: ENGAA Part A Mathematics and Physics Q20 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q20",
    duplicateQuestionIds: ["nsaa-2018-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 99.6%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q21-nsaa-q15",
    title: "2018: ENGAA Part A Mathematics and Physics Q21 and NSAA Part A Mathematics Q15",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q21",
    duplicateQuestionIds: ["nsaa-2018-s1-q15"],
    notes: "Automated text comparison of the official PDFs scored 96.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q22-nsaa-q31",
    title: "2018: ENGAA Part A Mathematics and Physics Q22 and NSAA Part B Physics Q31",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q22",
    duplicateQuestionIds: ["nsaa-2018-s1-q31"],
    notes: "Automated text comparison of the official PDFs scored 98.8%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q23-nsaa-q16",
    title: "2018: ENGAA Part A Mathematics and Physics Q23 and NSAA Part A Mathematics Q16",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q23",
    duplicateQuestionIds: ["nsaa-2018-s1-q16"],
    notes: "Automated text comparison of the official PDFs scored 96.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q24-nsaa-q33",
    title: "2018: ENGAA Part A Mathematics and Physics Q24 and NSAA Part B Physics Q33",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q24",
    duplicateQuestionIds: ["nsaa-2018-s1-q33"],
    notes: "Automated text comparison of the official PDFs scored 98%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q25-nsaa-q17",
    title: "2018: ENGAA Part A Mathematics and Physics Q25 and NSAA Part A Mathematics Q17",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q25",
    duplicateQuestionIds: ["nsaa-2018-s1-q17"],
    notes: "Automated text comparison of the official PDFs scored 94.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q26-nsaa-q34",
    title: "2018: ENGAA Part A Mathematics and Physics Q26 and NSAA Part B Physics Q34",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q26",
    duplicateQuestionIds: ["nsaa-2018-s1-q34"],
    notes: "Automated text comparison of the official PDFs scored 96.4%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q29-nsaa-q73",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q29 and NSAA Part E Advanced Mathematics and Advanced Physics Q73",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q29",
    duplicateQuestionIds: ["nsaa-2018-s1-q73"],
    notes: "Automated text comparison of the official PDFs scored 98.5%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q30-nsaa-q74",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q30 and NSAA Part E Advanced Mathematics and Advanced Physics Q74",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q30",
    duplicateQuestionIds: ["nsaa-2018-s1-q74"],
    notes: "Automated text comparison of the official PDFs scored 91.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q31-nsaa-q75",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q31 and NSAA Part E Advanced Mathematics and Advanced Physics Q75",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q31",
    duplicateQuestionIds: ["nsaa-2018-s1-q75"],
    notes: "Automated text comparison of the official PDFs scored 98%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q32-nsaa-q76",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q32 and NSAA Part E Advanced Mathematics and Advanced Physics Q76",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q32",
    duplicateQuestionIds: ["nsaa-2018-s1-q76"],
    notes: "Automated text comparison of the official PDFs scored 95.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q33-nsaa-q77",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q33 and NSAA Part E Advanced Mathematics and Advanced Physics Q77",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q33",
    duplicateQuestionIds: ["nsaa-2018-s1-q77"],
    notes: "Automated text comparison of the official PDFs scored 98.7%. Treated as the same question.",
  },
  {
    id: "dup-2018-engaa-q34-nsaa-q78",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q34 and NSAA Part E Advanced Mathematics and Advanced Physics Q78",
    verified: false,
    canonicalQuestionId: "engaa-2018-s1-q34",
    duplicateQuestionIds: ["nsaa-2018-s1-q78"],
    notes: "Automated text comparison of the official PDFs scored 93.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2018-engaa-q37-nsaa-q79",
    title: "2018: ENGAA Part B Advanced Mathematics and Advanced Physics Q37 and NSAA Part E Advanced Mathematics and Advanced Physics Q79",
    verified: true,
    canonicalQuestionId: "engaa-2018-s1-q37",
    duplicateQuestionIds: ["nsaa-2018-s1-q79"],
    notes: "Automated text comparison of the official PDFs scored 99.5%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q10-nsaa-q28",
    title: "2019: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q28",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q10",
    duplicateQuestionIds: ["nsaa-2019-s1-q28"],
    notes: "Automated text comparison of the official PDFs scored 97.5%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q17-nsaa-q11",
    title: "2019: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q11",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q17",
    duplicateQuestionIds: ["nsaa-2019-s1-q11"],
    notes: "Automated text comparison of the official PDFs scored 98.6%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q19-nsaa-q18",
    title: "2019: ENGAA Part A Mathematics and Physics Q19 and NSAA Part A Mathematics Q18",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q19",
    duplicateQuestionIds: ["nsaa-2019-s1-q18"],
    notes: "Automated text comparison of the official PDFs scored 97.6%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q21-nsaa-q73",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q21 and NSAA Part E Advanced Mathematics and Advanced Physics Q73",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q21",
    duplicateQuestionIds: ["nsaa-2019-s1-q73"],
    notes: "Automated text comparison of the official PDFs scored 98.2%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q22-nsaa-q74",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q22 and NSAA Part E Advanced Mathematics and Advanced Physics Q74",
    verified: false,
    canonicalQuestionId: "engaa-2019-s1-q22",
    duplicateQuestionIds: ["nsaa-2019-s1-q74"],
    notes: "Automated text comparison of the official PDFs scored 95.1%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2019-engaa-q23-nsaa-q75",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q23 and NSAA Part E Advanced Mathematics and Advanced Physics Q75",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q23",
    duplicateQuestionIds: ["nsaa-2019-s1-q75"],
    notes: "Automated text comparison of the official PDFs scored 98.6%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q24-nsaa-q76",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q24 and NSAA Part E Advanced Mathematics and Advanced Physics Q76",
    verified: false,
    canonicalQuestionId: "engaa-2019-s1-q24",
    duplicateQuestionIds: ["nsaa-2019-s1-q76"],
    notes: "Automated text comparison of the official PDFs scored 92.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2019-engaa-q27-nsaa-q77",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q27 and NSAA Part E Advanced Mathematics and Advanced Physics Q77",
    verified: true,
    canonicalQuestionId: "engaa-2019-s1-q27",
    duplicateQuestionIds: ["nsaa-2019-s1-q77"],
    notes: "Automated text comparison of the official PDFs scored 98.7%. Treated as the same question.",
  },
  {
    id: "dup-2019-engaa-q29-nsaa-q79",
    title: "2019: ENGAA Part B Advanced Mathematics and Advanced Physics Q29 and NSAA Part E Advanced Mathematics and Advanced Physics Q79",
    verified: false,
    canonicalQuestionId: "engaa-2019-s1-q29",
    duplicateQuestionIds: ["nsaa-2019-s1-q79"],
    notes: "Automated text comparison of the official PDFs scored 92.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2020-engaa-q1-nsaa-q2",
    title: "2020: ENGAA Part A Mathematics and Physics Q1 and NSAA Part A Mathematics Q2",
    verified: false,
    canonicalQuestionId: "engaa-2020-s1-q1",
    duplicateQuestionIds: ["nsaa-2020-s1-q2"],
    notes: "Automated text comparison of the official PDFs scored 95.5%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2020-engaa-q2-nsaa-q21",
    title: "2020: ENGAA Part A Mathematics and Physics Q2 and NSAA Part B Physics Q21",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q2",
    duplicateQuestionIds: ["nsaa-2020-s1-q21"],
    notes: "Automated text comparison of the official PDFs scored 97.7%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q6-nsaa-q28",
    title: "2020: ENGAA Part A Mathematics and Physics Q6 and NSAA Part B Physics Q28",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q6",
    duplicateQuestionIds: ["nsaa-2020-s1-q28"],
    notes: "Automated text comparison of the official PDFs scored 98.4%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q7-nsaa-q7",
    title: "2020: ENGAA Part A Mathematics and Physics Q7 and NSAA Part A Mathematics Q7",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q7",
    duplicateQuestionIds: ["nsaa-2020-s1-q7"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q8-nsaa-q30",
    title: "2020: ENGAA Part A Mathematics and Physics Q8 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q8",
    duplicateQuestionIds: ["nsaa-2020-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 99%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q9-nsaa-q10",
    title: "2020: ENGAA Part A Mathematics and Physics Q9 and NSAA Part A Mathematics Q10",
    verified: false,
    canonicalQuestionId: "engaa-2020-s1-q9",
    duplicateQuestionIds: ["nsaa-2020-s1-q10"],
    notes: "Automated text comparison of the official PDFs scored 92%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2020-engaa-q10-nsaa-q32",
    title: "2020: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q32",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q10",
    duplicateQuestionIds: ["nsaa-2020-s1-q32"],
    notes: "Automated text comparison of the official PDFs scored 97.8%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q11-nsaa-q11",
    title: "2020: ENGAA Part A Mathematics and Physics Q11 and NSAA Part A Mathematics Q11",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q11",
    duplicateQuestionIds: ["nsaa-2020-s1-q11"],
    notes: "Automated text comparison of the official PDFs scored 99.6%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q12-nsaa-q33",
    title: "2020: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q33",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q12",
    duplicateQuestionIds: ["nsaa-2020-s1-q33"],
    notes: "Automated text comparison of the official PDFs scored 97.7%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q13-nsaa-q14",
    title: "2020: ENGAA Part A Mathematics and Physics Q13 and NSAA Part A Mathematics Q14",
    verified: false,
    canonicalQuestionId: "engaa-2020-s1-q13",
    duplicateQuestionIds: ["nsaa-2020-s1-q14"],
    notes: "Automated text comparison of the official PDFs scored 95.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2020-engaa-q14-nsaa-q35",
    title: "2020: ENGAA Part A Mathematics and Physics Q14 and NSAA Part B Physics Q35",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q14",
    duplicateQuestionIds: ["nsaa-2020-s1-q35"],
    notes: "Automated text comparison of the official PDFs scored 97.6%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q15-nsaa-q16",
    title: "2020: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q16",
    verified: false,
    canonicalQuestionId: "engaa-2020-s1-q15",
    duplicateQuestionIds: ["nsaa-2020-s1-q16"],
    notes: "Automated text comparison of the official PDFs scored 92.6%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2020-engaa-q16-nsaa-q38",
    title: "2020: ENGAA Part A Mathematics and Physics Q16 and NSAA Part B Physics Q38",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q16",
    duplicateQuestionIds: ["nsaa-2020-s1-q38"],
    notes: "Automated text comparison of the official PDFs scored 99.5%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q17-nsaa-q17",
    title: "2020: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q17",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q17",
    duplicateQuestionIds: ["nsaa-2020-s1-q17"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q18-nsaa-q39",
    title: "2020: ENGAA Part A Mathematics and Physics Q18 and NSAA Part B Physics Q39",
    verified: true,
    canonicalQuestionId: "engaa-2020-s1-q18",
    duplicateQuestionIds: ["nsaa-2020-s1-q39"],
    notes: "Automated text comparison of the official PDFs scored 98.2%. Treated as the same question.",
  },
  {
    id: "dup-2020-engaa-q19-nsaa-q18",
    title: "2020: ENGAA Part A Mathematics and Physics Q19 and NSAA Part A Mathematics Q18",
    verified: false,
    canonicalQuestionId: "engaa-2020-s1-q19",
    duplicateQuestionIds: ["nsaa-2020-s1-q18"],
    notes: "Automated text comparison of the official PDFs scored 94.2%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2021-engaa-q1-nsaa-q1",
    title: "2021: ENGAA Part A Mathematics and Physics Q1 and NSAA Part A Mathematics Q1",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q1",
    duplicateQuestionIds: ["nsaa-2021-s1-q1"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q2-nsaa-q2",
    title: "2021: ENGAA Part A Mathematics and Physics Q2 and NSAA Part A Mathematics Q2",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q2",
    duplicateQuestionIds: ["nsaa-2021-s1-q2"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q5-nsaa-q5",
    title: "2021: ENGAA Part A Mathematics and Physics Q5 and NSAA Part A Mathematics Q5",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q5",
    duplicateQuestionIds: ["nsaa-2021-s1-q5"],
    notes: "Automated text comparison of the official PDFs scored 97.3%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q7-nsaa-q7",
    title: "2021: ENGAA Part A Mathematics and Physics Q7 and NSAA Part A Mathematics Q7",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q7",
    duplicateQuestionIds: ["nsaa-2021-s1-q7"],
    notes: "Automated text comparison of the official PDFs scored 98.2%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q8-nsaa-q29",
    title: "2021: ENGAA Part A Mathematics and Physics Q8 and NSAA Part B Physics Q29",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q8",
    duplicateQuestionIds: ["nsaa-2021-s1-q29"],
    notes: "Automated text comparison of the official PDFs scored 99.4%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q10-nsaa-q30",
    title: "2021: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q10",
    duplicateQuestionIds: ["nsaa-2021-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 99.3%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q12-nsaa-q31",
    title: "2021: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q31",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q12",
    duplicateQuestionIds: ["nsaa-2021-s1-q31"],
    notes: "Automated text comparison of the official PDFs scored 98.1%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q16-nsaa-q17",
    title: "2021: ENGAA Part A Mathematics and Physics Q16 and NSAA Part A Mathematics Q17",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q16",
    duplicateQuestionIds: ["nsaa-2021-s1-q17"],
    notes: "Automated text comparison of the official PDFs scored 99.7%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q18-nsaa-q19",
    title: "2021: ENGAA Part A Mathematics and Physics Q18 and NSAA Part A Mathematics Q19",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q18",
    duplicateQuestionIds: ["nsaa-2021-s1-q19"],
    notes: "Automated text comparison of the official PDFs scored 99.7%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q19-nsaa-q38",
    title: "2021: ENGAA Part A Mathematics and Physics Q19 and NSAA Part B Physics Q38",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q19",
    duplicateQuestionIds: ["nsaa-2021-s1-q38"],
    notes: "Automated text comparison of the official PDFs scored 99.1%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q20-nsaa-q21",
    title: "2021: ENGAA Part A Mathematics and Physics Q20 and NSAA Part A Mathematics Q21",
    verified: true,
    canonicalQuestionId: "engaa-2021-s1-q20",
    duplicateQuestionIds: ["nsaa-2021-s1-q21"],
    notes: "Automated text comparison of the official PDFs scored 99.8%. Treated as the same question.",
  },
  {
    id: "dup-2021-engaa-q21-nsaa-q40",
    title: "2021: ENGAA Part A Mathematics and Physics Q21 and NSAA Part B Physics Q40",
    verified: false,
    canonicalQuestionId: "engaa-2021-s1-q21",
    duplicateQuestionIds: ["nsaa-2021-s1-q40"],
    notes: "Automated text comparison of the official PDFs scored 91.2%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2022-engaa-q1-nsaa-q1",
    title: "2022: ENGAA Part A Mathematics and Physics Q1 and NSAA Part A Mathematics Q1",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q1",
    duplicateQuestionIds: ["nsaa-2022-s1-q1"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q10-nsaa-q30",
    title: "2022: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q10",
    duplicateQuestionIds: ["nsaa-2022-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 98.5%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q11-nsaa-q12",
    title: "2022: ENGAA Part A Mathematics and Physics Q11 and NSAA Part A Mathematics Q12",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q11",
    duplicateQuestionIds: ["nsaa-2022-s1-q12"],
    notes: "Automated text comparison of the official PDFs scored 99.5%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q14-nsaa-q35",
    title: "2022: ENGAA Part A Mathematics and Physics Q14 and NSAA Part B Physics Q35",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q14",
    duplicateQuestionIds: ["nsaa-2022-s1-q35"],
    notes: "Automated text comparison of the official PDFs scored 97.8%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q15-nsaa-q15",
    title: "2022: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q15",
    verified: false,
    canonicalQuestionId: "engaa-2022-s1-q15",
    duplicateQuestionIds: ["nsaa-2022-s1-q15"],
    notes: "Automated text comparison of the official PDFs scored 95.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2022-engaa-q16-nsaa-q36",
    title: "2022: ENGAA Part A Mathematics and Physics Q16 and NSAA Part B Physics Q36",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q16",
    duplicateQuestionIds: ["nsaa-2022-s1-q36"],
    notes: "Automated text comparison of the official PDFs scored 98.4%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q17-nsaa-q17",
    title: "2022: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q17",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q17",
    duplicateQuestionIds: ["nsaa-2022-s1-q17"],
    notes: "Automated text comparison of the official PDFs scored 99.3%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q19-nsaa-q19",
    title: "2022: ENGAA Part A Mathematics and Physics Q19 and NSAA Part A Mathematics Q19",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q19",
    duplicateQuestionIds: ["nsaa-2022-s1-q19"],
    notes: "Automated text comparison of the official PDFs scored 99.4%. Treated as the same question.",
  },
  {
    id: "dup-2022-engaa-q20-nsaa-q38",
    title: "2022: ENGAA Part A Mathematics and Physics Q20 and NSAA Part B Physics Q38",
    verified: true,
    canonicalQuestionId: "engaa-2022-s1-q20",
    duplicateQuestionIds: ["nsaa-2022-s1-q38"],
    notes: "Automated text comparison of the official PDFs scored 98.5%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q1-nsaa-q1",
    title: "2023: ENGAA Part A Mathematics and Physics Q1 and NSAA Part A Mathematics Q1",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q1",
    duplicateQuestionIds: ["nsaa-2023-s1-q1"],
    notes: "Automated text comparison of the official PDFs scored 100%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q4-nsaa-q24",
    title: "2023: ENGAA Part A Mathematics and Physics Q4 and NSAA Part B Physics Q24",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q4",
    duplicateQuestionIds: ["nsaa-2023-s1-q24"],
    notes: "Automated text comparison of the official PDFs scored 98.2%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q6-nsaa-q26",
    title: "2023: ENGAA Part A Mathematics and Physics Q6 and NSAA Part B Physics Q26",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q6",
    duplicateQuestionIds: ["nsaa-2023-s1-q26"],
    notes: "Automated text comparison of the official PDFs scored 98.2%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q7-nsaa-q7",
    title: "2023: ENGAA Part A Mathematics and Physics Q7 and NSAA Part A Mathematics Q7",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q7",
    duplicateQuestionIds: ["nsaa-2023-s1-q7"],
    notes: "Automated text comparison of the official PDFs scored 90.9%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2023-engaa-q8-nsaa-q28",
    title: "2023: ENGAA Part A Mathematics and Physics Q8 and NSAA Part B Physics Q28",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q8",
    duplicateQuestionIds: ["nsaa-2023-s1-q28"],
    notes: "Automated text comparison of the official PDFs scored 98%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q9-nsaa-q9",
    title: "2023: ENGAA Part A Mathematics and Physics Q9 and NSAA Part A Mathematics Q9",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q9",
    duplicateQuestionIds: ["nsaa-2023-s1-q9"],
    notes: "Automated text comparison of the official PDFs scored 96.8%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2023-engaa-q10-nsaa-q30",
    title: "2023: ENGAA Part A Mathematics and Physics Q10 and NSAA Part B Physics Q30",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q10",
    duplicateQuestionIds: ["nsaa-2023-s1-q30"],
    notes: "Automated text comparison of the official PDFs scored 98.1%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q11-nsaa-q11",
    title: "2023: ENGAA Part A Mathematics and Physics Q11 and NSAA Part A Mathematics Q11",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q11",
    duplicateQuestionIds: ["nsaa-2023-s1-q11"],
    notes: "Automated text comparison of the official PDFs scored 99.6%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q12-nsaa-q32",
    title: "2023: ENGAA Part A Mathematics and Physics Q12 and NSAA Part B Physics Q32",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q12",
    duplicateQuestionIds: ["nsaa-2023-s1-q32"],
    notes: "Automated text comparison of the official PDFs scored 98.3%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q13-nsaa-q13",
    title: "2023: ENGAA Part A Mathematics and Physics Q13 and NSAA Part A Mathematics Q13",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q13",
    duplicateQuestionIds: ["nsaa-2023-s1-q13"],
    notes: "Automated text comparison of the official PDFs scored 96%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2023-engaa-q14-nsaa-q34",
    title: "2023: ENGAA Part A Mathematics and Physics Q14 and NSAA Part B Physics Q34",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q14",
    duplicateQuestionIds: ["nsaa-2023-s1-q34"],
    notes: "Automated text comparison of the official PDFs scored 98.8%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q15-nsaa-q15",
    title: "2023: ENGAA Part A Mathematics and Physics Q15 and NSAA Part A Mathematics Q15",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q15",
    duplicateQuestionIds: ["nsaa-2023-s1-q15"],
    notes: "Automated text comparison of the official PDFs scored 94.3%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2023-engaa-q16-nsaa-q36",
    title: "2023: ENGAA Part A Mathematics and Physics Q16 and NSAA Part B Physics Q36",
    verified: true,
    canonicalQuestionId: "engaa-2023-s1-q16",
    duplicateQuestionIds: ["nsaa-2023-s1-q36"],
    notes: "Automated text comparison of the official PDFs scored 97.3%. Treated as the same question.",
  },
  {
    id: "dup-2023-engaa-q17-nsaa-q17",
    title: "2023: ENGAA Part A Mathematics and Physics Q17 and NSAA Part A Mathematics Q17",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q17",
    duplicateQuestionIds: ["nsaa-2023-s1-q17"],
    notes: "Automated text comparison of the official PDFs scored 96.7%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
  {
    id: "dup-2023-engaa-q18-nsaa-q38",
    title: "2023: ENGAA Part A Mathematics and Physics Q18 and NSAA Part B Physics Q38",
    verified: false,
    canonicalQuestionId: "engaa-2023-s1-q18",
    duplicateQuestionIds: ["nsaa-2023-s1-q38"],
    notes: "Automated text comparison of the official PDFs scored 96.7%. Very likely the same question; the remaining difference is usually PDF layout noise around diagrams and equations rather than different wording.",
  },
];

export const VERIFIED_DUPLICATE_GROUPS = PAST_PAPER_DUPLICATE_GROUPS.filter(
  (group) => group.verified,
);

export function groupsForYear(year: number): readonly PastPaperDuplicateGroup[] {
  return PAST_PAPER_DUPLICATE_GROUPS.filter((group) =>
    group.id.startsWith(`dup-${year}-`),
  );
}

/** Resolves a group's question ids into the mapped question records. */
export function groupQuestions(group: PastPaperDuplicateGroup) {
  const ids = [group.canonicalQuestionId, ...group.duplicateQuestionIds];
  return ids
    .map((id) => PAST_PAPER_QUESTION_MAP.find((entry) => entry.id === id))
    .filter((entry): entry is NonNullable<typeof entry> => Boolean(entry));
}
