#!/usr/bin/env python3
"""
Approve every successful row in a schema-prefix classifier JSONL using the model output
(same as “Approve” with default preview — no manual review UI).

Writes:
  <stem>_approved.json
  <stem>_review_state.json

  python approve_all_schema_prefix_jsonl.py schema_prefix_full.jsonl
  python approve_all_schema_prefix_jsonl.py schema_prefix_full.jsonl --output my_approved.json

Rows with ok: false are skipped (printed to stderr). Missing `block` in JSONL is filled from Schemas_ESAT.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_BASE = Path(__file__).resolve().parent
if str(_BASE) not in sys.path:
    sys.path.insert(0, str(_BASE))


def load_records(path: Path) -> list[dict]:
    out: list[dict] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if row.get("event") in ("run_start", "run_end"):
                continue
            if row.get("schema_id") and row.get("result") is not None:
                out.append(row)
    return out


def main() -> int:
    p = argparse.ArgumentParser(description="Auto-approve all OK rows in schema prefix JSONL")
    p.add_argument("jsonl", type=Path, help="Classifier JSONL (e.g. schema_prefix_full.jsonl)")
    p.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output approvals JSON (default: <stem>_approved.json next to JSONL)",
    )
    p.add_argument(
        "--base-dir",
        type=Path,
        default=_BASE,
        help="esat_question_generator root (for Schemas_ESAT.md when block missing)",
    )
    args = p.parse_args()

    if not args.jsonl.is_file():
        print(f"Not found: {args.jsonl}", file=sys.stderr)
        return 1

    from project import load_schemas_esat_markdown, parse_schemas_from_markdown

    from schema_prefix_common import build_final_block, new_schema_id_from_prefix

    _, md = load_schemas_esat_markdown(str(args.base_dir.resolve()))
    schemas = parse_schemas_from_markdown(md, allow_prefixes=("M", "P", "B", "C"))

    def block_for(r: dict) -> str:
        b = (r.get("block") or "").strip()
        if b:
            return r.get("block") or ""
        sid = (r.get("schema_id") or "").strip()
        ent = schemas.get(sid) or {}
        return ent.get("block") or ""

    records = load_records(args.jsonl)
    approvals: list[dict] = []
    decisions: dict[str, str] = {}
    approved_blocks: dict[str, str] = {}
    skipped = 0

    for r in records:
        if not r.get("ok"):
            skipped += 1
            continue
        sid = r.get("schema_id") or ""
        res = r.get("result") or {}
        block = block_for(r)
        if not block:
            print(f"Skip {sid}: no block in JSONL or Schemas_ESAT.md", file=sys.stderr)
            skipped += 1
            continue
        final_text = build_final_block(block, sid, res)
        rec = res.get("recommended_prefix", "M").strip().upper()[:1]
        new_id = new_schema_id_from_prefix(sid, rec)
        approvals.append(
            {
                "schema_id": sid,
                "new_schema_id": new_id,
                "recommended_prefix": rec,
                "original_block_markdown": block,
                "final_block_markdown": final_text,
            }
        )
        decisions[sid] = "approved"
        approved_blocks[sid] = final_text

    base = args.jsonl.parent
    stem = args.jsonl.stem
    out_path = args.output or (base / f"{stem}_approved.json")
    payload = {
        "source_jsonl": str(args.jsonl.resolve()),
        "approvals": approvals,
        "note": "auto-generated by approve_all_schema_prefix_jsonl.py (all OK rows)",
    }
    out_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    ap, rj = len(approvals), 0
    pe = sum(
        1
        for r in records
        if r.get("ok") and (r.get("schema_id") or "") not in decisions
    )
    st_path = base / f"{stem}_review_state.json"
    st_path.write_text(
        json.dumps(
            {
                "decisions": decisions,
                "approved_blocks": approved_blocks,
                "review_counts": {"approved": ap, "rejected": rj, "pending": pe},
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Approved {len(approvals)} schema(s) → {out_path.name}")
    print(f"Review state → {st_path.name}")
    if skipped:
        print(f"Skipped {skipped} row(s) (not ok or missing block).", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
